//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibDeviser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibDeviser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBase, SBML_GENERIC_SBASE
        ///Compartment, SBML_COMPARTMENT
        ///Constraint, SBML_CONSTRAINT
        ///SBMLDocument, SBML_DOCUMENT
        ///Event, SBML_EVENT
        ///EventAssignment, SBML_EVENT_ASSIGNMENT
        ///FunctionDefinition, SBML_FUNCTION_DEFINITION
        ///InitialAssignment, SBML_INITIAL_ASSIGNMENT
        ///KineticLaw, SBML_KINETIC_LAW
        ///ListOf, SBML_LIST_OF
        ///Model, SBML_MODEL
        ///Parameter, SBML_PARAMETER
        ///Reaction, SBML_REACTION
        ///Rule, SBML_RULE
        ///Species, SBML_SPECIES
        ///SpeciesReference, SBML_SPECIES_REFERENCE
        ///ModifierSpeciesReference, SBML_MODIFIER_SP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoreClasses {
            get {
                return ResourceManager.GetString("CoreClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %\documentclass{sbmlpkgspec}
        ///\documentclass[draftspec]{sbmlpkgspec}
        ///\frontNotice{\centering This is a working draft of release 1 of the specification for the package ``@@PACKAGENAME@@&apos;&apos; and not a normative document. Please send feedback to the Package Working Group mailing list at sbml-@@PACKAGENAME@@@lists.sourceforge.net.}
        ///
        ///\begin{document}
        ///
        ///\packageTitle{SBML Level 3 Package: @@PACKAGENAME@@ (`@@PACKAGENAME@@&apos;)}
        ///\packageVersion{Version 1, Release 1} \packageVersionDate{\today}
        ///
        ///\renewcommand\gra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
    }
}
